# Generated by Django 4.2.6 on 2023-11-17 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_employee_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='can_schedule',
            field=models.BooleanField(default=False),
        ),
    ]
