# Generated by Django 4.2.6 on 2023-11-28 20:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_start_time', models.TimeField()),
                ('m_end_time', models.TimeField()),
                ('t_start_time', models.TimeField()),
                ('t_end_time', models.TimeField()),
                ('w_start_time', models.TimeField()),
                ('w_end_time', models.TimeField()),
                ('th_start_time', models.TimeField()),
                ('th_end_time', models.TimeField()),
                ('f_start_time', models.TimeField()),
                ('f_end_time', models.TimeField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
