# Generated by Django 4.2.6 on 2023-12-01 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='f_end_time',
            field=models.TimeField(default='16:00:00'),
        ),
        migrations.AlterField(
            model_name='availability',
            name='f_start_time',
            field=models.TimeField(default='08:00:00'),
        ),
        migrations.AlterField(
            model_name='availability',
            name='t_end_time',
            field=models.TimeField(default='16:00:00'),
        ),
        migrations.AlterField(
            model_name='availability',
            name='t_start_time',
            field=models.TimeField(default='08:00:00'),
        ),
        migrations.AlterField(
            model_name='availability',
            name='th_end_time',
            field=models.TimeField(default='16:00:00'),
        ),
        migrations.AlterField(
            model_name='availability',
            name='th_start_time',
            field=models.TimeField(default='08:00:00'),
        ),
        migrations.AlterField(
            model_name='availability',
            name='w_end_time',
            field=models.TimeField(default='16:00:00'),
        ),
        migrations.AlterField(
            model_name='availability',
            name='w_start_time',
            field=models.TimeField(default='08:00:00'),
        ),
    ]
