# Generated by Django 4.2.6 on 2023-11-18 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeoffrequest',
            name='reason_choices',
            field=models.CharField(choices=[('choose', 'Choose'), ('vacation', 'Vacation'), ('health', 'Health'), ('school', 'School'), ('personal', 'Personal'), ('other', 'Other')], default='choose', max_length=10),
        ),
    ]
