# Generated by Django 4.2.6 on 2023-12-01 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='is_custom_photo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='photo',
            field=models.ImageField(default='default_photo.jpg', upload_to='blog/'),
        ),
    ]
