# Generated by Django 4.2.6 on 2023-10-20 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_employee_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='Last_name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='email',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='first_name',
        ),
    ]
