# Generated by Django 4.2.6 on 2023-10-25 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_employee_last_name_remove_employee_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('dateOfEmployment', models.DateField()),
                ('postalCode', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='announcement',
            name='author',
            field=models.CharField(default='Management', max_length=255),
        ),
        migrations.AddField(
            model_name='announcement',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
